model:
  class_path: "vv.models.Autoencoder"
  init_args:
  class_path: "vv.models.latent_diffusion_copy.VQModel"
  init_args:
    learning_rate: 4.5e-06
    embed_dim: 256
    n_embed: 1024
    split_quantizer: True
    num_spaces: 64
    distance_type: "l2"
    monitor: val/rec_loss
    ddconfig:
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: "vv.models.latent_diffusion_copy.loss.VQLPIPSWithDiscriminator"
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_num_layers: 2
        disc_start: 1
        disc_weight: 0.8
        codebook_weight: 1.0

